### PR TITLE
Create Registration

### LINKED ISSUE #23: Create Registration
Follow the [tutorial](https://ordinarycoders.com/blog/article/django-user-register-login-logout)

### PR DESCRIPTION
**Pull request by MelvinPariyadan**
Closes #23

### CODE REVIEW

**Review by LBeghini — COMMENTED** [review]
Can you provide any ways to test it?

**Comment by MelvinPariyadan** [comment]
@LBeghini Hey I just used postman and to check its functionality. I'll try to do proper testing soon. 
So after doing the tests similar to how we did it in algorithms assignment. How can I let SonarCloud know that I ran these test files cause I dont know how to work with SonarCloud?
By the way if you want to try out the endpoints in POSTMAN the http body for registration write
{
'username':x,
'password':x,
'first_name':x,
'email':x
}
you have to create a superuser in django and then you can do localhost/admin -> then you can see the changes in the database

**Comment by MelvinPariyadan** [comment]
Btw I wrote all the code first and then committed it as 3 parts so some dependencies maybe missing in each commits. Just pull all of the 3 commits and then it should work

**Comment by LBeghini** [comment]
> @LBeghini Hey I just used postman and to check its functionality. I'll try to do proper testing soon. So after doing the tests similar to how we did it in algorithms assignment. How can I let SonarCloud know that I ran these test files cause I dont know how to work with SonarCloud? By the way if you want to try out the endpoints in POSTMAN the http body for registration write { 'username':x, 'password':x, 'first_name':x, 'email':x } you have to create a superuser in django and then you can do localhost/admin -> then you can see the changes in the database

All right, I will clone and try to test it then. 
About the SonarCloud, it will automatically verify the tests once you commit them. [Here](https://realpython.com/testing-in-django-part-1-best-practices-and-examples/) there is a documentation you can follow to test the API.

By the way, what is the order the Pull Requests should be merged? I am thinking the proper order would be: 
1. Register
2. Login
3. Logout

If that is the case, please finish and try to fix (coding tests) for the registration part, and then merge one by one the other files to avoid conflicts.

**Comment by MelvinPariyadan** [comment]
@LBeghini  Hey commited in the order logout,login,registration,api documentation but there are no conflicts between these commits so the order shouldn't matter.

Yeah will try to fix the coding  tests

**Pull request merged**
